# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lzimmerm <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/01 11:44:08 by lzimmerm          #+#    #+#              #
#    Updated: 2019/04/01 11:44:09 by lzimmerm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file

SRCS=./main.c

all: $(NAME)

$(NAME):
		gcc $(CFLAGS) $(SRCS) -o $(NAME)

clean:
		rm -rf *.o

fclean:
		rm -rf $(NAME)

re: fclean all
